import type { DeveloperConfig } from "@/types";

export const DeveloperDetails: DeveloperConfig = {
  name: "Naved A. Sayyed",
  initials: "NS",
  designation: "Fullstack Developer",
  portfolio: "https://navedsayyed.me",
  email: "navedas9356@gmail.com",
  bio: "Hi World, I'm Naved A. Sayyed, a full-stack and mobile app developer from India passionate about building scalable and user-friendly applications. I specialize in React, React Native, Next.js, and TypeScript, focusing on clean architecture, performance, and modern UI/UX to create reliable web and mobile solutions.",
  avatar: "/navedsayyed.webp",
  resume: "https://navedsayyed.me/navedsayyed.pdf",
  socialLinks: [
    {
      name: "LinkedIn",
      url: "https://www.linkedin.com/in/naved-sayyed/",
      icon: "/social/linkedin.svg",
      hasDarkIcon: false,
      handle: "naved-sayyed",
    },
    {
      name: "GitHub",
      url: "https://github.com/navedsayyed",
      icon: "/social/github.svg",
      hasDarkIcon: true,
      handle: "navedsayyed",
    },
    {
      name: "X",
      url: "https://x.com/navedsayyed_",
      icon: "/social/twitter.svg",
      hasDarkIcon: false,
      handle: "navedsayyed_",
    },
    {
      name: "Instagram",
      url: "https://www.instagram.com/navedsayyed._",
      icon: "/social/instagram.svg",
      hasDarkIcon: false,
      handle: "navedsayyed._",
    },
  ],
  location: {
    city: "Nashik",
    country: "India",
  },
  seo: {
    title: "Naved A. Sayyed | Full Stack Developer from India",
    description:
      "Naved A. Sayyed is a Full Stack Developer from India specializing in React, Next.js, and TypeScript. Building accessible, high-performance web applications.",
    keywords: [
      "Naved A. Sayyed",
      "navedsayyed",
      "Naved A. Sayyed Full Stack Developer",
      "Full Stack Developer",
      "Full Stack Developer Nashik",
      "React Developer Nashik",
      "Next.js Developer",
      "TypeScript Developer",
      "MERN Stack Developer",
      "Web Developer Nashik",
      "Software Engineer Nashik",
      "Freelance Developer Nashik",
      "React",
      "Next.js",
      "TypeScript",
      "Node.js",
      "JavaScript",
      "Frontend Developer",
      "Backend Developer",
      "Mobile App Developer",
    ],
  },
  education: [
    {
      degree: "Bachelor of Computer Engineering",
      institution: "Guru Gobind Singh College of Engineering and Research Centre",
      logo: "/education/gcoerc.png",
      startDate: "2022",
      endDate: "2026",
      location: "Nashik, Maharashtra, India",
    },
    {
      degree: "Higher Secondary Education (10+2)",
      institution: "YEWS National High School and JR College",
      logo: "/education/National.png",
      startDate: "2020",
      endDate: "2022",
      location: "Nashik, Maharashtra, India",
    },
  ],
};
