import type { DeveloperConfig } from "@/types";

export const DeveloperDetails: DeveloperConfig = {
  name: "Naved A. Sayyed",
  initials: "NS",
  designation: "Full-Stack & Mobile Developer",
  portfolio: "https://navedsayyed.me",
  email: "navedas9356@gmail.com",
  bio: "Hi World, I'm Naved A. Sayyed, a full-stack and mobile app developer from India passionate about building scalable and user-friendly applications. I specialize in React, React Native, Next.js, and TypeScript, focusing on clean architecture, performance, and modern UI/UX to create reliable web and mobile solutions.",
  avatar: "/navedsayyed.webp",
  resume: "https://navedsayyed.me/navedsayyed.pdf",
  socialLinks: [
    {
      name: "LinkedIn",
      url: "https://www.linkedin.com/in/naved-sayyed/",
      icon: "/social/linkedin.svg",
      hasDarkIcon: false,
      handle: "naved-sayyed",
    },
    {
      name: "GitHub",
      url: "https://github.com/navedsayyed",
      icon: "/social/github.svg",
      hasDarkIcon: true,
      handle: "navedsayyed",
    },
    {
      name: "X",
      url: "https://x.com/navedsayyed_",
      icon: "/social/twitter.svg",
      hasDarkIcon: false,
      handle: "navedsayyed_",
    },
    {
      name: "Instagram",
      url: "https://www.instagram.com/navedsayyed._",
      icon: "/social/instagram.svg",
      hasDarkIcon: false,
      handle: "navedsayyed._",
    },
  ],
  location: {
    city: "Nashik",
    country: "India",
  },
  seo: {
    // This description is what Google prints under the title. Keep it under ~160 characters
    // or it gets truncated mid-sentence, and lead with the name so it bolds on name searches.
    title: "Naved A. Sayyed | Full Stack & Mobile Developer from India",
    description:
      "Naved A. Sayyed is a full-stack and mobile developer from Nashik, India, building production apps with React Native, Next.js, TypeScript and Supabase.",
    keywords: [
      "Naved A. Sayyed",
      "navedsayyed",
      "Naved A. Sayyed Full Stack Developer",
      "Full Stack Developer",
      "Full Stack Developer Nashik",
      "React Native Developer",
      "React Native Developer India",
      "Mobile App Developer Nashik",
      "React Developer Nashik",
      "Next.js Developer",
      "TypeScript Developer",
      "Web Developer Nashik",
      "Software Engineer Nashik",
      "Freelance Developer Nashik",
      "React Native",
      "Expo",
      "React",
      "Next.js",
      "TypeScript",
      "Supabase",
      "Node.js",
      "Python",
      "FastAPI",
      "JavaScript",
      "Frontend Developer",
      "Backend Developer",
      "Mobile App Developer",
    ],
  },
  education: [
    {
      degree: "Bachelor of Computer Engineering",
      institution: "Guru Gobind Singh College of Engineering and Research Centre",
      logo: "/education/gcoerc.png",
      startDate: "2022",
      endDate: "2026",
      location: "Nashik, Maharashtra, India",
    },
    {
      degree: "Higher Secondary Education (10+2)",
      institution: "YEWS National High School and JR College",
      logo: "/education/National.png",
      startDate: "2020",
      endDate: "2022",
      location: "Nashik, Maharashtra, India",
    },
  ],
};
